web: export PATH="/nix/var/nix/profiles/default/bin:/usr/bin:/usr/local/bin:$PATH" && python3 -m uvicorn main:app --host 0.0.0.0 --port $PORT || python -m uvicorn main:app --host 0.0.0.0 --port $PORT || chmod +x start.sh && ./start.sh

